import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// 复制 styles.css 到插件目录
function copyStyles() {
	const vaultPluginPath = "/Users/zhanglu/WorkBuddy/MDOrganization/obsidian-dev-sandbox/heatmap/.obsidian/plugins/obsidian-note-heatmap/";
	const stylesSource = "./styles.css";
	const stylesTarget = path.join(vaultPluginPath, "styles.css");
	
	try {
		if (fs.existsSync(stylesSource)) {
			fs.copyFileSync(stylesSource, stylesTarget);
			console.log("[build] styles.css copied to vault plugin folder");
		}
	} catch (err) {
		console.error("[build] Failed to copy styles.css:", err.message);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	copyStyles();
	process.exit(0);
} else {
	await context.rebuild();
	copyStyles();
	await context.watch();
}
