import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// 复制 styles.css 到插件目录
function copyStyles() {
	// 从环境变量获取 vault 路径，或使用默认相对路径
	const vaultPath = process.env.OBSIDIAN_VAULT_PATH || "../.obsidian";
	const pluginId = "note-heatmap"; // 与 manifest.json 中的 id 一致
	const vaultPluginPath = path.join(vaultPath, "plugins", pluginId);
	const stylesSource = "./styles.css";
	const stylesTarget = path.join(vaultPluginPath, "styles.css");
	
	// 确保目标目录存在
	try {
		if (!fs.existsSync(vaultPluginPath)) {
			fs.mkdirSync(vaultPluginPath, { recursive: true });
			console.log(`[build] Created plugin directory: ${vaultPluginPath}`);
		}
	} catch (err) {
		console.error(`[build] Failed to create plugin directory ${vaultPluginPath}:`, err.message);
		return;
	}
	
	try {
		if (fs.existsSync(stylesSource)) {
			fs.copyFileSync(stylesSource, stylesTarget);
			console.log(`[build] styles.css copied to ${stylesTarget}`);
		} else {
			console.warn(`[build] styles.css source not found at ${stylesSource}`);
		}
	} catch (err) {
		console.error("[build] Failed to copy styles.css:", err.message);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	copyStyles();
	process.exit(0);
} else {
	await context.rebuild();
	copyStyles();
	await context.watch();
}
